### ISSUE TITLE
Utf-8 problem when exporting under MAC-OS-X

### ISSUE THREAD

**Issue by vincentkollebolle** [oxfordinternetinstitute/gephi-plugins#11]
I export a graph (about the basic income), and get troubles with all the accentuation
(yep in french we have accent ;( ) in the resulting sigmaJS website.  

Eg:  "Le revenu de base est un droit inali�nable, ". (see also linked screenshot). 

Every meta looks fine : 
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta charset="utf-8">

I am using Gephi 0.8.2 beta with the Sigma Exporter 1.1.1 on Mac OSX 10.6.8. 
I am visiting the resulting website with Google Chrome Version 26.0.1410.43. 
![Capture d e cran 2013-03-29 a 15 06 28](https://f.cloud.github.com/assets/2372957/317596/022cfe4a-987a-11e2-95d5-b2fd327befa7.png)

**Comment by vincentkollebolle** [comment]
I just find a workaround. The json is exported as ISO-88...., use a text editor to change the format to UTF-8.
It seems it fixed the problem.

**Comment by vincentkollebolle** [comment]
ERRATA : the workaround does'nt function. Every accent is skipped.

**Comment by jthrilly** [comment]
@vincentkollebolle thanks for reporting this (and for your interest in the plugin). I've seen this behaviour with sigma in other scenarios, so I am going to go out on a limb and suggest this is a sigma issue, and not an issue with the plugin directly. There really is no excuse to not handle UTF-8 correctly, so I will investigate the issue and let you know if I can find a fix. Thanks again.

**Comment by jthrilly** [comment]
Just to make sure I am fixing the issue that affects you, could you supply your json file?

**Comment by jthrilly** [comment]
Can you confirm that the data displays correctly in the data lab view in Gephi? I suspect this may infact be a Gephi bug (see: gephi/gephi/issues/474). Gephi seems to not respect the BOM (or at least not interpret it correctly). If open a correctly encoded graphml file, it is displayed incorrectly in Gephi. If I then export the file using the plugin, this incorrect encoding remains. I believe this could be the source of your issue. We could potentially fix the plugin by forcing utf-8 (or else doing better detection) while waiting for Gephi to fix this bug.

**Comment by vincentkollebolle** [comment]
Hi @jthrilly you said : "thanks for reporting this (and for your interest in the plugin)" i can only say, the job done on your plugin is just SO GOOD ! so I am the one who say thanks :) 

Here is my data.json : http://pastebin.com/3tz3rgnr
Here is my config.json : http://pastebin.com/Ed6i9RWd

I can confirm that the problem is not present in the data view of gephi (see screenshot). 

![Capture d e cran 2013-03-29 a 19 14 22](https://f.cloud.github.com/assets/2372957/318573/bc365cd8-989c-11e2-8bfe-b463ebbf08d8.png)

When i look the encoding format of the exported json in Smultron (a raw text editor) i can see it in "Encodage ISO latin 1" (see capture 2) 
![Capture d e cran 2013-03-29 a 19 17 22](https://f.cloud.github.com/assets/2372957/318593/190d60e6-989d-11e2-90dd-7559bf9b8e57.png)

I am going to look if it could be the bug you tell me in gephi.

**Comment by vincentkollebolle** [comment]
I'am really sorry but I can't understand the gephi bug (it seems I don't have the knowledge level for it :'( ) 
I don't really get it in fact ;'(

**Comment by computermacgyver** [comment]
No worries about the gephi bug. The information you've provided is great
and super useful. I think we'll be able to get to the bottom of the issue.

## 

Sent from a mobile device. Apologies for spelling errors and/or brevity.

**Comment by computermacgyver** [comment]
This is indeed my error (combined with the defaults of Mac). Turns out the constructor for FileWriter uses the system default for character encoding. For me on linux this was UTF-8 but guessing it might be different on Mac/Windows. (ref: http://stackoverflow.com/questions/1001540/how-to-write-a-utf-8-file-with-java)

Josh / Vincent could you try this version of the plugin on Mac?
http://users.ox.ac.uk/~shil3231/utf8/uk-ac-ox-oii-sigmaexporter.nbm

For me on Linux it's producing output like:
http://users.ox.ac.uk/~shil3231/utf8/network/
(which also hopefully displays correctly for you?!)

**Comment by fouillis** [comment]
Thanks a lot.
I'm french too and had the same issue on Windows.
It's seems to be correct now with the version of the plugin you proposed for mac.

**Comment by vincentkollebolle** [comment]
I'am sorry, I stil have the problem ... as seen in this screenshot : 
![Capture d e cran 2013-04-03 a 17 10 23](https://f.cloud.github.com/assets/2372957/334578/d911582a-9c76-11e2-8591-deeab0973573.png)

I give you again the json file : 
data.json : http://pastebin.com/WkJrQkfa
config.json : http://pastebin.com/E3qcDTxa 

This time both file are showed as encoded in unicode (UTF-8) in Smultron. 
I hope i'am not disturbing a lot :(

**Comment by vincentkollebolle** [comment]
I tried with the last version of gephi, and the plugin you gave me.

**Comment by computermacgyver** [comment]
Fixed in v1.2 (Aug 2013). https://marketplace.gephi.org/plugin/sigmajs-exporter/
