### ISSUE TITLE
Question: is there a way to make the label appear even if there is no hovering on them ? 

### ISSUE THREAD

**Issue by vincentkollebolle** [oxfordinternetinstitute/gephi-plugins#12]
I am looking for a way to say make the label apear directly when someone load the page.
( http://ledebat.revenudebase.info). I let the question here in case someone already done that, if not at the time I find it, il will post the answer here. Promess !

**Comment by computermacgyver** [comment]
What do you mean by "label"? The left hand box with the title, description,
etc? Node labels? The right hand panel with node details?

## 

Sent from a mobile device. Apologies for spelling errors and/or brevity.

**Comment by vincentkollebolle** [comment]
Sorry I answer late, I am talking about the Node label. When I point my mouse on a specifique node, the label appear, in my case I would like the node label to be always shown (hover on them or not). May-be it's more a sigma question ?

**Comment by computermacgyver** [comment]
No problem. This is something that can already be done, but the properties are not fully exposed in the plugin. You'll need to open the config.json file in a text editor (e.g. notepad) and edit the `"labelThreshold": 10,` line. Changing it to `"labelThreshold": 0,` should make all labels visible immediately as in [this example](http://oxfordinternetinstitute.github.com/InteractiveVis/network/?config=config_ukgov.json). 

In general, you might have to play with the value a little bit to find something appropriate for each graph. The threshold is the minimal size a node must be to be labeled. Additional nodes are labeled when the user zooms in. If the value is too small and the node labels can overlap and be unreadable. Too large and not enough nodes are labeled.

**Comment by vincentkollebolle** [comment]
Perfect I report that in the wiki, so we can close this ticket :)

**Comment by computermacgyver** [comment]
Thanks for the work on the wiki! I realize now that labelThreshold should actually be 0 to make sure all labels are shown (i.e. even a node with size 0.5 or something).  I've changed this in the comment above already.
