### ISSUE TITLE
What brings the $GP data into the fancy box ?

### ISSUE THREAD

**Issue by vincentkollebolle** [oxfordinternetinstitute/gephi-plugins#13]
Another Question, I try to understand the source code (even if I don't really understand javascript) to do something specific and be abble to complete the wiki page of this github.

But I don't understand manythings.
- It's seems that the data printed in the right panel (attributepane) comes from the $GP variable. How does it function ? What brings the data from $GP to #attributepane ? 

I would like to do something like this : 
Inside Gephi > Data Lab  all the record got a "url" columns. I would like to ajax load the content accessible at this url for each node in the right columns. (if you click on a specific node, the content accessible via the linked url is loaded with jquery.get(url) and printed. 

Do you think it's possible ? 
Did I miss something ? 

again: great great job !

**Comment by computermacgyver** [comment]
That's a good idea. Would the content at the URL be shown exactly as is
(I.e. in an iframe) or would the URL be json or other data to be consumed
and displayed differently?

## 

Sent from a mobile device. Apologies for spelling errors and/or brevity.

**Comment by computermacgyver** [comment]
P.S. I'll get the full answer to your question when I'm on my laptop and
not tablet.

## 

Sent from a mobile device. Apologies for spelling errors and/or brevity.

**Comment by computermacgyver** [comment]
The code admittedly could use some better documentation -- sorry. The data is stored in Sigma and is pulled out in the nodeActive(...) function in main.js. In particular, the [variable "b"](https://github.com/oxfordinternetinstitute/InteractiveVis/blob/f47f49f54c961c99940e983fd53145226223e0e0/network/js/main.js#L542) is the active node and "f" holds it's attributes dictionary. In [this loop](https://github.com/oxfordinternetinstitute/InteractiveVis/blob/f47f49f54c961c99940e983fd53145226223e0e0/network/js/main.js#L563) the html for the labels and values is constructed.

**Comment by computermacgyver** [comment]
See 
https://github.com/oxfordinternetinstitute/InteractiveVis/commit/47316d751fe8a379468df1b4cfe8eeeb1268241d
for a quick and dirty way to do this. Just replace main.js with [the new version](https://raw.github.com/oxfordinternetinstitute/InteractiveVis/iframe_attr/network/js/main.js)

This will give you something like:
http://users.ox.ac.uk/~shil3231/utf8/network_iframe/

The attribute to be in the iframe must be called url (all lowercase). You might want to adjust the height of the iframe to your liking.
