### ISSUE TITLE
Unable to export edge attributes

### ISSUE THREAD

**Issue by chrisentery** [oxfordinternetinstitute/gephi-plugins#16]
I have an extra column in edges that I would like to export.  This seems to be lost during the export process.  Additionally, I've tried to export edge labels, but during the export the edge labels seem to be reset to the edge id.

**Comment by computermacgyver** [comment]
Thanks, Chrisentery, for reporting this. You're right in the current implementation that extra edge columns and edge labels are not exported. 

Were you using JSONExporter or SigmaExporter?

Off hand, I think the edge information should be added to the JSONExporter but not to SigmaExporter given that the bundled HTML/JS in the SigmaExporter doesn't currently display any of the additional edge data.  Does that make sense?

**Comment by chrisentery** [comment]
Thanks for your reply!  I tried both exporters, actually, and neither exports any attributes, although the SigmaExporter contains an empty attributes list (ie. "attributes":{})

**Comment by computermacgyver** [comment]
Fixed in v1.2 of the JSONExporter. 
SigmaExporter still doesn't include edge attributes because they aren't used / exposed anywhere in it.
https://marketplace.gephi.org/plugin/json-exporter/
