### ISSUE TITLE
format

### ISSUE THREAD

**Issue by hdean83** [oxfordinternetinstitute/gephi-plugins#22]
Is it possible to change the formatting, such as the margin at the top of the group selector box?  Right now, there is a bunch of unused space, and it's causing the selector to be offscreen.

**Comment by jthrilly** [comment]
Hi

Thanks for taking an interest in the plugin!

You should be able to achieve what you describe by editing the file 'style.css' which is located in the css folder of your output. I suggest using your browser debug tools to isolate the specific css rules you need to modify ('inspect element' and the like in google chrome). If I recall correctly, the group select box is positioned relative to the button which opens it, so the modifications might be more involved than simply changing the margin. Let me know if you have any difficulties and I'll see if I can help.
