### ISSUE TITLE
Group Selector By Edge?

### ISSUE THREAD

**Issue by hdean83** [oxfordinternetinstitute/gephi-plugins#23]
Hi - I would like to be able to group select by edge type - would it be possible to recode for that after exporting?  Or, is there a way in the initial export menu?

Also, when I export, the edge partitioning is not preserved and instead, colors of edges seem to be corresponding to node color partitioning.  Is there a way to fix that in the code?

Thanks so much for your help,
Hannah

**Comment by computermacgyver** [comment]
From v1.2 (Aug 2013) of the SigmaExporter plugin, edge color is pulled directly from the values set in Gephi; so, hopefully this will address your second question.

The group selector is built to select groups of nodes. There is no easy way to make a changes to edges, but one possibility would be to edit the main.js file to have lists of different nodes (e.g., all nodes that need to be shown for edge type A, all nodes that need to be shown for edge type B, etc.) and load these as discussed in #21 .
