### ISSUE TITLE
Symmetry problems

### ISSUE THREAD

**Issue by Caddarik** [oxfordinternetinstitute/gephi-plugins#25]
Hello,

It seems that Sigmajs operate an horizontal symmetry of the Gephi graph (top <--> bottom).
It's not a big issue but the points of references change from interactive Sigmajs map to static map export from Gephi...

Sigmajs exporter is really a great tool !
Good continuation,
Cédric

**Comment by computermacgyver** [comment]
Thanks for filing this. The underlying sigma.js library using a different coordinate system than Gephi; it looked like sigma might change the coordinate system upstream, but change is slow; so I might just change the exporter to adjust the coordinates between the two systems at the time of export. #5 duplicates this issue; so I'm closing this one.
