### ISSUE TITLE
Group Selectors [enhancement]

### ISSUE THREAD

**Issue by Caddarik** [oxfordinternetinstitute/gephi-plugins#26]
Hello,

I'm using Gephi 0.8.2 in windows and Sigmajs 1.1.1

It's should be fine if for the group selector :
- the appropriate labels (those use in Gephi) are use in Sigmajs instead of Group 1, Group 2...
- we could select several Group selectors to have several choice of partitioning in Sigmajs

Meanwhile could you indicate how to change manually the group selectors labels in the Sigmajs template ?
I investigate in the index.html, main.js but haven't find the solution

Thank you for your work,
Cédric

**Comment by computermacgyver** [comment]
Hi Caddarik,

I'm glad you find the tool useful. Please see [this issue report on the group selector title](https://github.com/oxfordinternetinstitute/gephi-plugins/issues/21#issuecomment-18977778) for a temporary workaround.

Scott
