### ISSUE TITLE
encoding problem [bug]

### ISSUE THREAD

**Issue by Caddarik** [oxfordinternetinstitute/gephi-plugins#27]
Hello,

I'm using Gephi 0.8.2 and Sigmajs exporter 1.1.1 in windows vista

It seems to be an encoding problem
apostrophe and accentuate characters... appears as a ? for the nodes labels, the title, the legend...
Even though there is no problem in Gephi for the node label

Meanwhile could you indicate how to change manually Sigmajs template to solve this issue ?

Thanks a lot,
Cédric

**Comment by computermacgyver** [comment]
Could you please try the beta version of the plugin referenced [in this issue](https://github.com/oxfordinternetinstitute/gephi-plugins/issues/11#issuecomment-15705989).  Apparently Windows and Mac don't use Unicode as the default encoding for files as on Linux. The version linked above forces a UTF-8 encoding for the data file and should address the issue. If it does not, please let me know so I can dig further. Thanks!
