### ISSUE TITLE
sigma.js drop down group selecter

### ISSUE THREAD

**Issue by hdean83** [oxfordinternetinstitute/gephi-plugins#28]
Hi - I would like to manually change the layout in a couple of ways, but needed a bit of help doing so:
1. change the drop down menu to an always visible check off menu
2. make it so that nodes outside a single node's clicked network remain faded but still visible even when a node is clicked on in order to view the data linked to that node.

Thanks for any help you can provide.

Hannah

**Comment by computermacgyver** [comment]
Thanks for suggesting these additions. There is a 'dim' option for hover that works like this for mouse hover. Extending this to the mouse click is probably pretty straightforward. I've created a new issue for this: #31 

Changing the panel to be always open is probably also straightforward in main.js, but I'm not sure how much use/demand there is for this. If you can add it to [main.js](https://github.com/oxfordinternetinstitute/InteractiveVis/blob/master/network/js/main.js) and [config.json](https://github.com/oxfordinternetinstitute/InteractiveVis/blob/master/network/config.json) as an option I'd be happy to pull the change and incorporate it into the plugin for other users.

**Comment by hdean83** [comment]
Hi - Thanks for your response.  I successfully edited the main.js on one
dynamic output about a month ago, but when I went to create another today,
with the same edits to the code, the output is not working.  Have there
been changes that would prevent employing these types of edits to the
main.js?

Thanks for your help.

On Fri, Aug 9, 2013 at 3:38 AM, computermacgyver
notifications@github.comwrote:

> Thanks for suggesting these additions. There is a 'dim' option for hover
> that works like this for mouse hover. Extending this to the mouse click is
> probably pretty straightforward. I've created a new issue for this: #31https://github.com/oxfordinternetinstitute/gephi-plugins/issues/31
> 
> Changing the panel to be always open is probably also straightforward in
> main.js, but I'm not sure how much use/demand there is for this. If you can
> add it to main.jshttps://github.com/oxfordinternetinstitute/InteractiveVis/blob/master/network/js/main.jsand
> config.jsonhttps://github.com/oxfordinternetinstitute/InteractiveVis/blob/master/network/config.jsonas an option I'd be happy to pull the change and incorporate it into the
> plugin for other users.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/oxfordinternetinstitute/gephi-plugins/issues/28#issuecomment-22379647
> .

## 

Hannah Dean
Department of Environmental, Earth and Ocean Sciences (EEOS)
University of Massachusetts Boston
100 Morrissey Blvd.
Boston, MA 02125-3393, USA

**Comment by computermacgyver** [comment]
Hi hdean, there haven't been any edits to the main.js in the plugin in the last couple months (there have been [a few edits to the github version](https://github.com/oxfordinternetinstitute/InteractiveVis/blob/master/network/js/main.js)). 

There was a bug with the "dim" option (#8) that was corrected recently. Before, "Dim" and not "dim" was written to config.json if selected as the hover option for node behavior. Depending on the changes you're making and your selection for "node hover behavior", this may affect you. Try changing the node hover behvior to default or edit the config.json to change it back to "Dim" if your code edits need this.

Other than that change I can't think of anything that would affect this. If you post your code, I'll be happy to take a look and see if I can spot anything.
