### ISSUE TITLE
nodes too small and labels won't display

### ISSUE THREAD

**Issue by rjordan65** [oxfordinternetinstitute/gephi-plugins#30]
I'm just starting out with Gephi, so please excuse me if the solution is painfully obvious.  Looking at my visualization in Gephi on both the overview and preview tabs, my labels are properly displayed and my nodes are sized relative to betweenness centrality from 50-100.  When I export to a Sigma.js template, I set image attribute to "Id," yet when I open the index file using Firefox, my nodes are super tiny and the labels aren't visible unless clicked upon.  What am I doing wrong here?  Thanks for the assistance.
![untitled](https://f.cloud.github.com/assets/5186883/929296/8681ac7e-ffd9-11e2-8de0-949093731db1.jpg)

**Comment by computermacgyver** [comment]
Hi rjordan65,

There are some properties of sigma that are hard to get good defaults for, and they seem to be off for your case. To adjust, please open the config.json file generated from the exporter in a text editor (e.g., notepad). Look for the lines that read:

```
"minNodeSize": 1,
"maxNodeSize": 7,
```

. These are the smallest and largest node sizes for the graph. Sigma will the sizes from gephi to fit this range. Try adjusting these up (e.g., `"minNodeSize": 5,  "maxNodeSize": 20,`), saving the file, and refreshing your browser. You'll probably have to experiment a bit to find the best numbers for your graph.

In the same config.json file, there is also a `"labelThreshold": 10,` property. Nodes smaller than the value given here will not have their labels drawn until the user zooms or clicks them. Setting this to 0 or 1 will make all your labels always shown.

**Comment by rjordan65** [comment]
Thanks so so much.  Everything is working perfectly now.  You're the man.

**Comment by computermacgyver** [comment]
No worries. Glad it worked.
