### ISSUE TITLE
Newbie: Image Attributes

### ISSUE THREAD

**Issue by TimeBandit** [oxfordinternetinstitute/gephi-plugins#32]
Hello,

Can someone please explain the process of adding images at attributes which can later be viewed as a node property when the export is made.

Regards,

 TimeBandit

**Comment by computermacgyver** [comment]
Hi,

Each node will need an attribute that has the full or relative url to an image. This can be manipulated in the "Data Laboratory" section of Gephi. If the files are not on your server, please make sure that all the urls in the column for your image begin with `http://` or `https://`. If the files on are the same server, it can be just the name of the picture if they will be in the same directory/folder as the index.html file or it can be something like `folder_name/image.jpg` if the files will be in a subfolder.

Once that is set, launch the export dialogue (File->Export->sigma.js template) and select the column with the urls in the dropdown menu next to the "Image attribute?" prompt.

That should be all that is needed. It is worth noting that the code doesn't do anything to resize the images; so, if the images are quite large, you may want to copy them and resize the copies to a smaller size. Depending if you're on Linux, Mac, or Windows there are different programs that can batch/bulk resize an entire folder of pictures in one go.

Hope this helps,
Scott

**Comment by TimeBandit** [comment]
Great. It worked perfect thanks!
