### ISSUE TITLE
Shortest path between two nodes

### ISSUE THREAD

**Issue by naourass** [oxfordinternetinstitute/gephi-plugins#33]
Hello, I'm new to Gephi and Sigma.js and I was wondering if is there a way to show with Sigma.js  the shortest path between 2 nodes like Shown in Gephi when selecting 2 nodes?

**Comment by computermacgyver** [comment]
Welcome, and I hope you're finding both Sigma and Gephi helpful. Sigma is more limited in what is pre-programmed. I haven't written the functionality to show shortest paths, but this could be done by someone with some JavaScript programming experience. I can add it to the features request list, but I'm not sure if/when I would have time to look at it. If anyone else wants to add it, I'd be happy to incorporate it into the project.

**Comment by naourass** [comment]
Yes they are very usefull, good continuation for this great project.
