### ISSUE TITLE
Showing nodes color in the sidebar (Entred in error)

### ISSUE THREAD

**Issue by naourass** [oxfordinternetinstitute/gephi-plugins#34]
Hello, I'm trying to add a small pill showing the color of every node in the connections bar,  I Tried this:
f.push('<li class="membership"><div class="smallpill" style="background: ' + c.colour +'"></div><a href="#' + c.name + '" onmouseover="sigInst._core.plotter.drawHoverNode(sigInst._core.graph.nodesIndex[\'' + c.id + '\'])\" onclick=\"nodeActive(\'' + c.id + '\')" onmouseout="sigInst.refresh()">' + c.name + "</a></li>");
The problem is that "c.colour" shows the color of the connected edge. I need to show the color of the node not the color of the edge, I don't really have a javascript experience, how can i fix this please?

**Comment by computermacgyver** [comment]
Closing to answer in #35
