### ISSUE TITLE
Sigmajs exporter broken

### ISSUE THREAD

**Issue by TimeBandit** [oxfordinternetinstitute/gephi-plugins#36]
Hi, My network seems to have broken the exporter once it began to get past a few hundred nodes. Many of the edges are not visible in the export. It looks a mess. I will send my network file to anyone who can look into it. I've attached a snap of the network.
![nw](https://f.cloud.github.com/assets/2059850/1277727/8b818c80-2edc-11e3-84b5-fbc75cad5457.PNG)
# My config file looks like this

{
  "type": "network",
  "version": "1.0",
  "data": "data.json",
  "logo": {
    "text": "",
    "file": "",
    "link": ""
  },
  "text": {
    "title": "",
    "more": "This is the family tree of Mian Ramzany who decended into Moran Heeran in Onah from Kashmir in the year 1870(Bicram). \nMian Jamal Din resided at Mora, Dadyal. Sahib Din, Qaim Din and Wahab Din resided in Mora Janjilan and Razaq Mir resided at Dhoke Rakh. ",
    "intro": "Click on any dot or zoom-in using a mouse wheel for more information.\nSpouses are next each other if they had children together regardless of whether they are now deceased or seperated."
  },
  "legend": {
    "edgeLabel": "",
    "colorLabel": "",
    "nodeLabel": ""
  },
  "features": {
    "search": true,
    "groupSelectorAttribute": false,
    "hoverBehavior": "default"
  },
  "informationPanel": {
    "imageAttribute": false,
    "groupByEdgeDirection": false
  },
  "sigma": {
    "graphProperties": {
      "minEdgeSize": 0.2,
      "maxNodeSize": 7,
      "maxEdgeSize": 0.5,
      "minNodeSize": 1
    },
    "drawingProperties": {
      "labelThreshold": 10,
      "hoverFontStyle": "bold",
      "defaultEdgeType": "curve",
      "defaultLabelColor": "#000",
      "defaultLabelHoverColor": "#fff",
      "defaultLabelSize": 14,
      "activeFontStyle": "bold",
      "fontStyle": "bold",
      "defaultHoverLabelBGColor": "#002147",
      "defaultLabelBGColor": "#ddd"
    },
    "mouseProperties": {
      "minRatio": 0.75,
      "maxRatio": 20
    }
  }
}

**Comment by TimeBandit** [comment]
Here is a better image of whats going on. The edges are all there but the colours a all confused.

![capture](https://f.cloud.github.com/assets/2059850/1277774/7c26e034-2edf-11e3-98df-095878f31896.JPG)

**Comment by computermacgyver** [comment]
Hi TimeBandit,

Sorry for the delay. As far as edge size goes, try to adjust the `minEdgeSize` property in your config.json (you can open it with any text editor [e.g., notepad):
    "minEdgeSize": 0.4,
    "maxEdgeSize": 1,

If an edge has been assigned a color in Gephi that color will be transfered to Sigma.js. If not, the edge color is the same as its source node. The only way I can think that some edges would be white right now is that some color was set for them in Gephi. Nonetheless, perhaps the easier way to work around this for now is to continue editing the config.json file and under `drawingProperties` add a line like:
     "defaultEdgeColor": "#000",
which would make all the edges black.

If this doesn't work and the visualization is live on a server, could you put the link here or send via email? Then I can  dig a bit more and verify what I propose will work for you.

**Comment by TimeBandit** [comment]
Sorry, your suggestion did not work. What I could do is just to email you my Gephi file. If it works on your station; its not the software. What do you think

**Comment by computermacgyver** [comment]
Just emailed you back the file. It seems deleting any previous output or choosing a new output directory resolves this. I was unable to reproduce the issue on my machine.

**Comment by TimeBandit** [comment]
Already tried thus but will try again.
