### ISSUE TITLE
Need documentation -- help welcome :-)

### ISSUE THREAD

**Issue by computermacgyver** [oxfordinternetinstitute/gephi-plugins#4]
Anyone welcome to help --- just start here on the Wiki tab :-)

**Comment by vincentkollebolle** [comment]
What is the most important to describe ?

**Comment by computermacgyver** [comment]
Thanks for the help with the wiki. I think one basic help for the wiki would be a screenshot of the export window and a screenshot of the resulting webpage with arrows connecting / explaining the inputs in the export window. 

I'll try to create a new page that describes more of the sigma options that could be edited in the config.json since these aren't available through the GUI (although maybe I should just make them available through the GUI)
