### ISSUE TITLE
arrow for the directed graph

### ISSUE THREAD

**Issue by ldkingvivi** [oxfordinternetinstitute/gephi-plugins#40]
is that possible to show arrow for the directed graph ?

Right now even though the GEXF shows the graph is directed, there's still no arrow on the web interface, is there a way to show that or right now we only support undirected edges ?

**Comment by computermacgyver** [comment]
Edges are directed, but the default edge type of 'curved edges' make them very hard to see. [Changing to straight/line edges](https://github.com/oxfordinternetinstitute/gephi-plugins/wiki) makes them more visible.
