### ISSUE TITLE
Updating sigma.js plugin

### ISSUE THREAD

**Issue by edgonzalez32** [oxfordinternetinstitute/gephi-plugins#41]
I was wondering if I could get some guidance on how to update sigma.js that Gephi exports. I've tried copying the current sigma.js file (1.0) overtop the version the plugin exports (0.1). The reason why is I'm trying to use the force atlas plugin with sigma. However, I was told that I would need to update sigma.js.

I suppose another part of my question would be do you have any plans to release an updated plugin for Gephi? Thanks in advance.

**Comment by computermacgyver** [comment]
At the moment, the simplest solution is probably to use [the earlier 0.1 version of the force atlas plugin](https://github.com/oxfordinternetinstitute/sigma.js/blob/master/plugins/sigma.forceatlas2.js).

The interface for sigma.js has changed substantially between the versions, which means it isn't just a matter of substituting one file for another. I do plan to update the plugin to use the latest version, but this won't be until next month at the earliest.
