### ISSUE TITLE
Any way a user can select two nodes to display?

### ISSUE THREAD

**Issue by edgonzalez32** [oxfordinternetinstitute/gephi-plugins#42]
Is there a way to add an option so that the user can click two nodes to see the connections?

**Comment by computermacgyver** [comment]
This isn't currently possible, I'm afraid. If you or a friend have some JavaScript experience, [the code is open here](/oxfordinternetinstitute/InteractiveVis/blob/master/network/js/main.js), and I would be happy to incorporate an enhancement to do this.
