### ISSUE TITLE
Encoding problems

### ISSUE THREAD

**Issue by rornor** [oxfordinternetinstitute/gephi-plugins#45]
Hi,
I'm on Windowns, and if I export Gephi graph to sigma-js and load it locally everything is perfect, but if I upload the contents to a http storage (i.e. dropbox or other), characters other then ascii display garbage.

I thought that problem is maybe in fancybox (ruled out jquery obviously), but after some modifications it seems that problem is here. Strangely I didn't find any issue reporting encoding problems.

What do you think, makes the code render fine locally and then spit garbage from server?

**Comment by rornor** [comment]
This seems like a bug. Problem is that data.json file doesn't have BOM header and if I add it, it's read fine again (so luckily problem is simply solvable).
So after-all you read json data with those couple of lines js code, and could export data.json file with BOM.

**Comment by computermacgyver** [comment]
Thanks, rornor, this. What version of Java do you have installed on your machine? The file should be encoded in UTF-8, in which case a BOM is optional and discouraged by the [Unicode standard (p.30)](http://www.unicode.org/versions/Unicode5.0.0/ch02.pdf). I'll have to get a Windows machine to do a bit of testing I guess. Thanks for reporting.

**Comment by rornor** [comment]
Hi,

file is encoded in UTF-8, but without BOM. As mentioned this doesn't pose problem if I load result locally. If I upload the project to server, then I see the problem, which is solvable if I add BOM header to data.json file.

I run Windows 8 with this java version:

```
>java -version
java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)
```
