### ISSUE TITLE
Implementation of the SVG renderer plugin

### ISSUE THREAD

**Issue by novastra** [oxfordinternetinstitute/gephi-plugins#49]
Hello,

I am trying to figure out the place where the following lines of code should be implemented to get a svg export of the graph from <a href="https://github.com/jacomyal/sigma.js/tree/master/plugins/sigma.exporters.svg">the sigma repository</a>. 

This in HTML : <button id="export" type="export" onclick="expt()">Export</button>

And this in main.js :

function expt() {
 sigInst.toSVG({download: true, filename: 'mygraph.svg', size: 1000});
};

Why it doesn't work?

**Comment by computermacgyver** [comment]
sigma.exporters.svg is for a different version of sigma.js than is currently implemented in our plugin and hence the two are incompatible.  (Sigma.js had a big rewrite last year that is not yet incorporated in the plugin). If you need to use sigma.exporters.svg, you will not be able to use this plugin (until the plugin is re-written). You may consider generating, the SVG with other software (e.g., it is straightforward to generate an SVG in Gephi), porting the svg exporter to the version of sigma used in the plugin, or using one of the examples from the sigma.js page to replace the plugin output.

**Comment by novastra** [comment]
Thank you for your answer, I will try to port the exporter and add it to GH here latter.
For now I am working on a script to create a new canvas from 2 or 3 canvases present with Sigma and then convert this only one canvas to PNG.
