### ISSUE TITLE
Sigma.js fails on large network

### ISSUE THREAD

**Issue by marianoju** [oxfordinternetinstitute/gephi-plugins#53]
I am trying to export a large network with 115,000+ nodes and 2,500,000+ edges that I have been editing with Gephi 0.8.2 (see [exported JPG](http://extrazoom.com/image-45234.html)). [JSON file](https://www.dropbox.com/s/ucpv4i1af9vfn6q/data.json?dl=0) size is 347.4 MB. This is a screenshot of the index.html displayed with Firefox 41.0.1: 

![screenshot - 10142015 - 04 24 29 pm_mod](https://cloud.githubusercontent.com/assets/6254428/10486891/717d1c78-7291-11e5-87a5-64717b6c0ae4.png)
- No network is displayed. 
- The link “More about this visualisation” is unresponsive. 
- The search function is unresponsive. 
- The “Group Selector” shows no groups. (There should be about 70) 

[This is the original GDF file](https://www.dropbox.com/s/nmj4fbkxnmrtqha/all_groups_2013-10-03_short.gdf?dl=0) and [this the GEPHI file after editing](https://www.dropbox.com/s/rzc50egul2edmqu/all_groups_2013-10-03_short_OpenOrd.gephi?dl=0). 

I have also exported a JSON file using [JSON Exporter](https://marketplace.gephi.org/plugin/json-exporter/) and fed this JSON file to Sigma.js but the result is the same. [JSON file](https://www.dropbox.com/s/tf0rpj7f7wccu56/all_groups_2013-10-03_short_OpenOrd.json?dl=0) size is 355 MB. 

I have tested the setting with a smaller network (using the [“CPAN authors” dataset](https://github.com/gephi/gephi/wiki/Datasets) with 800+ nodes and 2000+ edges) and it works just fine. 

Is this a known problem with Sigma.js? Is there a (file size) limit? Any solution?

I am using Linux Mint 17 Xfce (64-bit).

**Comment by computermacgyver** [comment]
The JS/HTML load the entire data.json file and display the results in the browser. There is not a programmed limit, but a practical limit is created by the capabilities of the browser/system. It seems like you've exceeded the limits of what Firefox will render on your computer.

You might try with the latest version of [sigma.js](https://github.com/jacomyal/sigma.js/) and/or the [linkjurious.js](https://github.com/Linkurious/linkurious.js/) port. Both of these have some optimizations that are not yet bundled into the exporter. Another option is to only load subsets of the network (something that the commercial linkurio.us product does).

**Comment by marianoju** [comment]
Thanks for your quick reply, @computermacgyver. I just wanted to add that I have been in contact with Sébastien Heymann from Linkurious, and he stated that Linkurious can _display_ only networks (or subsets of networks) of a few thousands nodes.
