### ISSUE TITLE
Gephi 0.9

### ISSUE THREAD

**Issue by aadjanson** [oxfordinternetinstitute/gephi-plugins#56]
Will the gephi plugin be updated to version 0.9?

Aad Janson

**Comment by computermacgyver** [comment]
Yes, the plugin will be updated for 0.9 as soon as  the new plugin architecture is stable and documented. http://www.github.com/gephi/gephi-plugins

**Comment by computermacgyver** [comment]
The plugin has been migrated and is awaiting approval.
https://github.com/gephi/gephi-plugins/pull/74

**Comment by computermacgyver** [comment]
@aadjanson Wanted to let you know that the plugin has now been incorporated into Gephi 0.9.x and is ready for use. You will find it under Tools->Pluings.
