### ISSUE TITLE
Display edge labels?

### ISSUE THREAD

**Issue by okcomputerik** [oxfordinternetinstitute/gephi-plugins#58]
Is there any relatively easy way I can get edge labels displayed with the sigma exporter plug-in? I know sigma has a plug-in to achieve that (https://github.com/jacomyal/sigma.js/tree/master/plugins/sigma.renderers.edgeLabels), but my js programming skills are pretty basic, so trying to get anything done directly with sigma is probably out of the question for me right now (yes, I've tried but haven't gotten too far...).

Any help would be much appreciated!
Ricardo

**Comment by computermacgyver** [comment]
Hi Ricardo,

There isn't an easy solution at this point. We are in the process of reworking some aspects of the plugin, and I will add this to the list of possible new features to add. I'm sorry not to have a quick answer right now. 

One thing we could look into is putting the edge labels in the right info pane (after clicking on a node) that would be more straightforward for the moment, but I don't know if that would address your use case.

Cheers,
Scott

**Comment by okcomputerik** [comment]
Hi Scott,

Thanks for the quick response! It's a pity this isn't implemented yet, but I'm really looking forward to it happening - I really love your plug-in.

If your proposal of adding them to the right info pane is easier to implement for the time being, then so be it (and, actually,I think it could be a neat solution since it wouldn't clutter the graph with text everywhere in case there are lots of edges). Would they work as the Connections right now? I mean, would it be possible to have them highlighted (together with the nodes they connect maybe?) whenever you hover over them, and to zoom on the connecting nodes on click, for instance?

Cheers!
Ricardo

**Comment by triplingual** [comment]
I needed to do something similar, and bashed around until I got this hack to `js/main.js`.
The first part of the hack is lines 10–13 of the gist, and the second part is lines 78–92.

https://gist.github.com/triplingual/19673847307158ca3e451918a56030ab

This works only when a node is active, and pulls out an attribute particular to our dataset of all the edges whose target is the active node (using a filter). The relevant attribute values are rolled up and formatted, then stuffed into the title attribute of the HTML for the list of connected nodes in the information pane. The label, IIRC, is in `sigInst._core.graph.edges[your-edge-id].label`, but I'm no sigma scholar. I'm also no JavaScript genius, so there may be hidden performance traps or other issues with this hack.

**Comment by photomedia** [comment]
A graph is composed of nodes and edges.  It seems obvious to me that displaying edge labels is just as important and essential as displaying node labels.  Displaying them on the "Information" pane after clicking on a node would be OK, but not having any labels whatsoever for any of the edges is a significant limitation of this export plugin.

**Comment by OminousAnemone** [comment]
Does anyone have a workaround (even a hacky one) for this? I tried the suggestion from @triplingual but couldn't get it to work.

For reference my code is here: https://github.com/OminousAnemone/MoonGraph

**Comment by computermacgyver** [comment]
There is a plugin for edge labels in the Simga.js repository:
https://github.com/jacomyal/sigma.js/tree/master/plugins/sigma.renderers.edgeLabels

This is for a newer version of Sigma.js than the version used in this plugin, which is no longer maintained. They might be compatible, but you're probably better off starting with examples/tutorials on the [sigmajs website](http://sigmajs.org/)
