### ISSUE TITLE
image of node not exporting

### ISSUE THREAD

**Issue by bgriffen** [oxfordinternetinstitute/gephi-plugins#59]
Hi, I have published a graph of wikipedia which can be found [here](http://brendangriffen.com/assets/thinkers/). I noticed there is a broken image link but I can't seem to find a way to connect up the image links in postprocessing. I thought I could just edit the data.json file but it seems it can not be loaded into python's json importer because of the encodings. You'll also notice in the graph that there aren't the correct encodings.

1) what attribute needs to be adjusted such that the image is displayed correctly. See attached image. Can I load these in post-processing?

2) why isn't the encoding executing correctly as all foreign names contain "?" within them for each node. See attached image.

![issue](https://cloud.githubusercontent.com/assets/2667869/13683976/a788735c-e6d7-11e5-9c03-bb1548941d71.png)

Thanks in advance.

**Comment by computermacgyver** [comment]
Apologies for the delay. I will look into this. It should export the JSON in UTF-8. There used to be issues on Windows but not Mac or Linux that I thought were fixed, but perhaps not.

The attribute holding the location of the image is specified in the config.json file. It should be possible to just edit data.json with Python as you suggest once we get the encoding sorted. 

Just to verify, this is with Gephi 0.9.x?
