### ISSUE TITLE
Can somebody explain how to properly upload this ouput (which runs fine locally) to a website? [JS not working]

### ISSUE THREAD

**Issue by ghost** [oxfordinternetinstitute/gephi-plugins#60]
I am specifically trying to upload this to a github page, and whenever I point to the index.html file all I get is the plain text not the actual graph.

**Comment by computermacgyver** [comment]
For a standard server, just upload the files via FTP, etc. GitHub is trickier. See the documentation about GitHub Pages at https://pages.github.com/ . Basically you have to create a detached branch named gh-pages and put the files in that branch. I can't explain it all from my mobile, but give it a try and reopen this issue if you run into difficulties.

**Comment by ghost** [comment]
Hmm, tried create a gh-pages branch and uploading the files, still didn't work. Any reason you could think of why if the same process would work for a normal ftp upload?

**Comment by computermacgyver** [comment]
Can you get a simple hello world HTML page to load correctly? Could you also include a link to the repository / pages? If a simple HTML page works, then the network should work fine as well.

**Comment by ghost** [comment]
Hi,

I did get it to work eventually.

https://github.com/joshash/joshash.github.io

But how would I go about hosting two graphs?

I tried adding a gh-pages and putting a new folder in there and linking to
that second index.html file but that didn't work and just made the page
throw an error so I deleted it. Any idea why making a gh-pages branch, a
seperate folder, and a second index.html within that folder wouldn't work?

Damn, I should really learn more about web stuff.

**Comment by computermacgyver** [comment]
It is the data.json and config.json files that contain the actual data and display information about the graph. So, it is not enough to just create a second index.html page.

The easiest thing is to simply create a new directory with all the files. i.e., export a second network from Gephi, rename the directory/folder "network" to "network2" and add this in the same way you added the existing "network" directory.
