### ISSUE TITLE
exporting existing gephi file into sigma.js Export

### ISSUE THREAD

**Issue by anandg112** [oxfordinternetinstitute/gephi-plugins#61]
Hi, I am new to gephi. I have downloaded your sigma.js export plugin and have a few questions. I have an existing gephi file that I would like to make interactive and view-able online. After I export to sigma.js template, a new folder "network" is created. I see that there is an existing data .json file in the folder but gephi can export only in .csv format and does not have size, x, or y attributes. Am I missing something here? How do I upload my own network data into your plugin?

**Comment by computermacgyver** [comment]
The data.json file is your network data. The plugin interfaces with Gephi to export the data in JSON format; so there shouldn't be anything further needed from you.

Chrome has some security restrictions that mean the network won't be shown when the files are opened locally, but you can preview the network with Firefox. All major browsers will show the network correctly once the files are uploaded to a webserver.

**Comment by anandg112** [comment]
Thanks, much appreciated. I got it to work after running it on a webserver on Chrome.
