### ISSUE TITLE
hover over edge <-> Putting edge information on right info pane

### ISSUE THREAD

**Issue by vulpessepluv** [oxfordinternetinstitute/gephi-plugins#65]
I was wondering, if there is a possibility to show information about an edge on the info pane?
Ideally it would be very similar to clicking on a node with the information display following.

The 2013 Issue posted by psychemedia (https://github.com/oxfordinternetinstitute/InteractiveVis/issues/50) is very close to my request, so if the code for this is actually available and fitting I'd be more than happy to be on the receiving end!

Greets, v

**Comment by computermacgyver** [comment]
Responded at https://github.com/oxfordinternetinstitute/InteractiveVis/issues/50 . If the issue involves showing multiple attributes for an edge, feel free to continue here. If it involves one attribute, the other issue thread is probably better.
