### ISSUE TITLE
0.9 support

### ISSUE THREAD

**Issue by hvandenb** [oxfordinternetinstitute/gephi-plugins#69]
When will the plug-in be updated to the latest Gephi?

**Comment by computermacgyver** [comment]
The plugin is already available for 0.9. It was one of the first plugins available for the new version over a year ago. Install from the plugin menu in Gephi.

**Comment by hvandenb** [comment]
@computermacgyver Thanks I found it in Gephi. It was not listed on the Gephi website yet.

![image](https://cloud.githubusercontent.com/assets/401017/24588269/48c671ac-1782-11e7-9bac-9b34a169cd3b.png)

**Comment by computermacgyver** [comment]
There are no 0.9 plugins in marketplace.gephi.org . The site is old and only kept for users still using 0.8x. It could do with a proper notice saying this, but I do not have any control over it.
