### ISSUE TITLE
How do you embed sigma folder items in Wordpress site?

### ISSUE THREAD

**Issue by Jburrett** [oxfordinternetinstitute/gephi-plugins#70]
I've tried uploading the Index file and putting the code into < iframe> but I don't get the network, just a few titles and things.  Do I have also upload the data file, css, js files?

**Comment by computermacgyver** [comment]
All the files included in the zip file are necessary for the network to render properly. I would recommend that you upload all the files to a standard webserver and then include the address of this webserver in an iframe link on your WordPress site. If you change the directory/folder structure, the paths in index.html and config.json would need to be updated. It is possible to host the network on GitHub as well (https://pages.github.com/).
