### ISSUE TITLE
Delete labels and limit amount of information in information pane

### ISSUE THREAD

**Issue by leo1aimpact** [oxfordinternetinstitute/gephi-plugins#71]
Hi 
How to turn off labels when I don't hover the mouse over them and how to limit information which appears on information pane?
When I increased size of nodes through config file labels appears for some nodes 
<img width="722" alt="screen shot 2017-07-03 at 01 43 06" src="https://user-images.githubusercontent.com/14843009/27773724-43b4a47a-5f91-11e7-9297-1ee6937b1e71.png">

**Comment by computermacgyver** [comment]
In the config.json file, you can increase the "[labelThreshold](https://github.com/oxfordinternetinstitute/InteractiveVis/blob/master/network/config.json#L39)" value. A large value will hide labels until the network is zoomed in (and node size increases). Alternatively, you can add:
```
"drawLabels":false,
```
to the config.json file in the same section to disable labels.

For the information pane on the right side, it is easiest to create a copy of your network in Gephi, delete columns you do not want to appear from the Data Laboratory screen, and then export your network. If you are updating an already exported network, you can just copy over the new data.json file.

**Comment by leo1aimpact** [comment]
Thank you for your answers, Scott!

The thing is that I need to calculate size parameters and adjust color using some of these columns, so, if I delete them from data laboratory I will not be able to use them as size and color parameters, but for end users, these columns don't provide any meaning and that's why I was asked to delete them from infirmation pane

**Comment by computermacgyver** [comment]
Hi Leonid, 

You should still be able to delete these values after setting the size/colors of nodes, which would be the easiest course of action and also result in a faster experience for end users as duplicate data would not be included in the file.

Alternatively, you can edit the [for loop that constructs the attribute panel](https://github.com/oxfordinternetinstitute/InteractiveVis/blob/master/network/js/main.js#L585). In particular, you could add an if statement to check the value of attr and skip/include certain attributes only.

**Comment by leo1aimpact** [comment]
Oh, I see, thank you so much for your help Scott!

**Comment by computermacgyver** [comment]
No problem!
