### ISSUE TITLE
Changing "Connections" labels

### ISSUE THREAD

**Issue by schignel** [oxfordinternetinstitute/gephi-plugins#73]
Is it possible to change the "Connections" labels from their defaults: "Mutual", "Incoming", and "Outgoing"?

**Comment by computermacgyver** [comment]
To do this, please open the js/main.js file in a text editor (e.g., notepad) and edit the relevant words starting at Line 551](https://github.com/oxfordinternetinstitute/InteractiveVis/blob/master/network/js/main.js#L553). E.g., change 

``f.push("<h2>Mututal (" + size + ")</h2>");
(size>0)? f=f.concat(createList(mutual)) : f.push("No mutual links<br>");``

to

``f.push("<h2>Bidirectional (" + size + ")</h2>");
(size>0)? f=f.concat(createList(mutual)) : f.push("No bidirectional edges<br>");``
