### ISSUE TITLE
Privacy violation by Google Analytics tracking in export

### ISSUE THREAD

**Issue by kannes** [oxfordinternetinstitute/gephi-plugins#77]
A page exported with this plugin spies on anyone who views it due to the following embedded tracking code:

```
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-21293169-4']);
  _gaq.push(['_setDomainName', 'none']);
  _gaq.push(['_setAllowLinker', true]);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
```

Please remove that, it is disrespectful and invasive. I am pretty sure this is not in accordance with the GDPR.

The offending template is in
https://github.com/oxfordinternetinstitute/gephi-plugins/blob/sigmaexporter-plugin/modules/sigmaExporter/src/main/resources/uk/ac/ox/oii/sigmaexporter/resources/network.zip

**Comment by computermacgyver** [comment]
This code is over 8 years old and no longer maintained. The use of Google Analytics to get an idea of how much the plugin was disclosed in the original documentation. I do not recommend using this code at this point in time: there is a whole new version of sigma.js that is much improved.
