### ISSUE TITLE
Is it possible to add Force Atlas into the export?

### ISSUE THREAD

**Issue by Esoppant** [oxfordinternetinstitute/gephi-plugins#79]
It appears from the sigma.js [repository](https://github.com/jacomyal/sigma.js) that the sigma.js library includes application of the Force Atlas 2 layout. Is there a GUI-aided way for laymen to apply this on exports from Gephi? I'm guessing not since the export menu for SigmaExport in Gephi is rather simplistic. What would be the next best method? Adding Force Atlas 2 code in the config.json file that is generated by SigmaExport?

(Asking because the node labels in my exports look too close together, and I'd like to fix that by manually distancing the nodes)

**Comment by computermacgyver** [comment]
For the problem of node labels appearing too close together, you might try to use the "Expand" layout option in Gephi and simply move all nodes a bit further apart.

There isn't a GUI driven way to include the Force Atlas 2 sigma.js algorithm, but the HTML and JavaScript code generated can be modified. Only the data.json and config.json files are updated if you re-export the network. So, changes elsewhere will persistent. That said, this project is no longer actively maintained; so, it may be better to take the data.json file and look at examples directly on the sigma.js website.
